import Head from "next/head";
import { useEffect } from "react";
import Feed from "../components/feed";
import SlideBar from "../components/slidebar";
import Widget from "../components/widget";

import { useAuthContext } from "../context/authContext";

import { useRouter } from "next/router";

export default function Home({ newsResult }) {
  const { user } = useAuthContext();

  return (
    <div className="">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen  mx-auto ">
        {/* Slideber */}
        <SlideBar user={user} />

        {/* Feed */}
        <Feed user={user} />

        {/* Widged */}
        <Widget newsResult={newsResult.articles} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const newsResult = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/sports/in.json"
  ).then((res) => res.json());

  return {
    props: { newsResult },
  };
}
